// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: ping-counter.proto

/* eslint-disable */

export const protobufPackage = "PingCounter";

export interface GetRequest {
}

export interface IncrementRequest {
}

export interface PingCounter {
  id: string;
  count: number;
  lastPingedAt: number;
  createdAt: number;
}

export interface PingCounterService {
  Get(request: GetRequest): Promise<PingCounter>;
  Increment(request: IncrementRequest): Promise<PingCounter>;
}
