// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: ping-counter.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "PingCounterGrpc";

export interface PingCounterGrpcGetRequest {
}

export interface PingCounterGrpcPingRequest {
}

export interface PingCounterGrpcPayload {
  id: string;
  count: number;
  lastPingedAt: number;
  createdAt: number;
}

export const PING_COUNTER_GRPC_PACKAGE_NAME = "PingCounterGrpc";

export interface PingCounterGrpcServiceClient {
  get(request: PingCounterGrpcGetRequest): Observable<PingCounterGrpcPayload>;

  ping(request: PingCounterGrpcPingRequest): Observable<PingCounterGrpcPayload>;
}

export interface PingCounterGrpcServiceController {
  get(
    request: PingCounterGrpcGetRequest,
  ): Promise<PingCounterGrpcPayload> | Observable<PingCounterGrpcPayload> | PingCounterGrpcPayload;

  ping(
    request: PingCounterGrpcPingRequest,
  ): Promise<PingCounterGrpcPayload> | Observable<PingCounterGrpcPayload> | PingCounterGrpcPayload;
}

export function PingCounterGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["get", "ping"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PingCounterGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PingCounterGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PING_COUNTER_GRPC_SERVICE_NAME = "PingCounterGrpcService";
