// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: ping-counter.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "PingCounterGrpc";

export interface PingCounterGrpcDTO {
  id: string;
  value: number;
  lastPingedAt: number;
}

export interface PingCounterGetGrpcInput {
}

export interface PingCounterPingGrpcInput {
}

export const PING_COUNTER_GRPC_PACKAGE_NAME = "PingCounterGrpc";

export interface PingCounterGrpcServiceClient {
  get(request: PingCounterGetGrpcInput): Observable<PingCounterGrpcDTO>;

  ping(request: PingCounterPingGrpcInput): Observable<PingCounterGrpcDTO>;
}

export interface PingCounterGrpcServiceController {
  get(
    request: PingCounterGetGrpcInput,
  ): Promise<PingCounterGrpcDTO> | Observable<PingCounterGrpcDTO> | PingCounterGrpcDTO;

  ping(
    request: PingCounterPingGrpcInput,
  ): Promise<PingCounterGrpcDTO> | Observable<PingCounterGrpcDTO> | PingCounterGrpcDTO;
}

export function PingCounterGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["get", "ping"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PingCounterGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PingCounterGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PING_COUNTER_GRPC_SERVICE_NAME = "PingCounterGrpcService";
